### ISSUE TITLE
riscv: disabling all default features in Cargo.toml

### ISSUE THREAD

**Issue by marcomaas1990** [hermit-os/hermit-rs-template#66]
Can you help me how to disable the default features in the Cargo.toml in the template project?
So that the build works without virtio support on riscv.

**Comment by mkroening** [comment]
Ah, sorry, I forgot to answer your last comment in https://github.com/hermit-os/loader/pull/345. Thanks for opening a new issue! :)

```toml
[target.'cfg(target_os = "hermit")'.dependencies]
hermit = { version = "0.9", default-features = false }
```

should work. See [The Cargo Book — Specifying Dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) for details.
